### ISSUE TITLE
Not Working on mg_koga73_multigames

### ISSUE THREAD

**Issue by Cruze03** [Kxnrl/MapMusic-API#1]
[MapMusic] Failed to open sound [mg_koga73_multigames/crystal collect.wav]
[MapMusic] Failed to open sound [mg_koga73_multigames/5.wav]
[MapMusic] Failed to open sound [mg_koga73_multigames/4.wav]
[MapMusic] Failed to open sound [mg_koga73_multigames/3.wav]
[MapMusic] Failed to open sound [mg_koga73_multigames/2.wav]
[MapMusic] Failed to open sound [mg_koga73_multigames/1.wav]
[MapMusic] Failed to open sound [player/vo/anarchist/radio_letsgo02.wav]
[MapMusic] Failed to open sound [mg_koga73_multigames/warproom.wav]

**Comment by Kxnrl** [comment]
try this

[FILE REMOED]

**Comment by Cruze03** [comment]
Yes working! :D
Can you provide .sp file and extension's .so file aswell?

**Comment by Cruze03** [comment]
?~

**Comment by Kxnrl** [comment]
when I use pc, I will upload that.

**Comment by Cruze03** [comment]
Needed extension's .so file too (that will work in linux server) :(
